"""add_border_radius_input_field

Revision ID: 0b7bfcfdff05
Revises: 3d37bb607cfe
Create Date: 2025-11-25 04:14:08.698423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b7bfcfdff05'
down_revision: Union[str, Sequence[str], None] = '3d37bb607cfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('border_radius_input', sa.Integer(), nullable=False, server_default='24'))
    op.drop_column('conversations', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('topic', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('chatbots', 'border_radius_input')
    # ### end Alembic commands ###
