"""add_website_links_table

Revision ID: 9b06cb356fbe
Revises: 20f75f2f4694
Create Date: 2025-11-23 17:43:02.974554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b06cb356fbe'
down_revision: Union[str, Sequence[str], None] = '20f75f2f4694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('website_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chatbot_uuid', sa.String(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('link_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chatbot_uuid'], ['chatbots.uuid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_links_chatbot_uuid'), 'website_links', ['chatbot_uuid'], unique=False)
    op.create_index(op.f('ix_website_links_url'), 'website_links', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_website_links_url'), table_name='website_links')
    op.drop_index(op.f('ix_website_links_chatbot_uuid'), table_name='website_links')
    op.drop_table('website_links')
    # ### end Alembic commands ###
