"""add_welcome_message_and_example_messages_to_chatbots

Revision ID: 9f83850e9c56
Revises: 487e2e141cf4
Create Date: 2025-11-27 03:50:25.357141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f83850e9c56'
down_revision: Union[str, Sequence[str], None] = '487e2e141cf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('welcome_message', sa.String(length=500), nullable=True))
    op.add_column('chatbots', sa.Column('example_messages', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbots', 'example_messages')
    op.drop_column('chatbots', 'welcome_message')
    # ### end Alembic commands ###
