"""add_subscription_and_credits_system

Revision ID: abf0e11ecea5
Revises: 0b7bfcfdff05
Create Date: 2025-11-25 05:26:23.088472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'abf0e11ecea5'
down_revision: Union[str, Sequence[str], None] = '0b7bfcfdff05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from datetime import datetime, timedelta
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('message_credits', sa.Integer(), nullable=False),
    sa.Column('features', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_name'), 'plans', ['name'], unique=True)
    
    # Insert default plans
    plans_table = sa.table('plans',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('display_name', sa.String),
        sa.column('description', sa.String),
        sa.column('price', sa.Float),
        sa.column('message_credits', sa.Integer),
        sa.column('features', sa.String),
        sa.column('is_active', sa.Boolean),
        sa.column('created_at', sa.DateTime)
    )
    
    op.bulk_insert(plans_table, [
        {
            'id': 1,
            'name': 'basic',
            'display_name': 'Basic',
            'description': 'Perfect for trying out our service',
            'price': 0.0,
            'message_credits': 50,
            'features': '{"features": ["50 messages/month", "1 chatbot", "Basic support"]}',
            'is_active': True,
            'created_at': datetime.utcnow()
        },
        {
            'id': 2,
            'name': 'starter',
            'display_name': 'Starter',
            'description': 'Great for small businesses',
            'price': 29.0,
            'message_credits': 1000,
            'features': '{"features": ["1,000 messages/month", "3 chatbots", "Priority support", "Custom branding"]}',
            'is_active': True,
            'created_at': datetime.utcnow()
        },
        {
            'id': 3,
            'name': 'pro',
            'display_name': 'Pro',
            'description': 'For growing teams',
            'price': 99.0,
            'message_credits': 5000,
            'features': '{"features": ["5,000 messages/month", "10 chatbots", "Priority support", "Custom branding", "Advanced analytics"]}',
            'is_active': True,
            'created_at': datetime.utcnow()
        },
        {
            'id': 4,
            'name': 'enterprise',
            'display_name': 'Enterprise',
            'description': 'For large organizations',
            'price': 299.0,
            'message_credits': 20000,
            'features': '{"features": ["20,000 messages/month", "Unlimited chatbots", "24/7 support", "Custom branding", "Advanced analytics", "Dedicated account manager"]}',
            'is_active': True,
            'created_at': datetime.utcnow()
        }
    ])
    
    # Add columns to users table with defaults
    op.add_column('users', sa.Column('plan_id', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('message_credits_remaining', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('users', sa.Column('credits_reset_date', sa.DateTime(), nullable=False, server_default=sa.text('NOW() + INTERVAL \'30 days\'')))
    op.add_column('users', sa.Column('subscription_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False, server_default='active'))
    op.create_index(op.f('ix_users_plan_id'), 'users', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'users', 'plans', ['plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_plan_id'), table_name='users')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'credits_reset_date')
    op.drop_column('users', 'message_credits_remaining')
    op.drop_column('users', 'plan_id')
    op.drop_index(op.f('ix_plans_name'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
